### ISSUE TITLE
Calling inRole() with an instance of Role

### ISSUE THREAD

**Issue by DanVeira** [cartalyst/sentinel#288]
This is your code:

```
    public function inRole($role)
    {
        foreach ($this->roles as $instance) {
            if ($role instanceof RoleInterface) {
                return $instance->getRoleId() === $role->getRoleId();
            }

            if ($instance->getRoleId() == $role || $instance->getRoleSlug() == $role) {
                return true;
            }
        }

        return false;
    }
```

Shouldn't it check all instances before returning false on the first iteration when the `$role` is an instance of `Role`?

Something like this:

```
    public function inRole($role)
    {
        foreach ($this->roles as $instance) {
            if ($role instanceof RoleInterface) {
                if ($instance->getRoleId() === $role->getRoleId()) {
                   return true;
                }
            } elseif ($instance->getRoleId() == $role || $instance->getRoleSlug() == $role) {
                return true;
            }
        }

        return false;
    }
```

I am pulling my hairs because sometimes it works and sometimes it doesn't and I've pinpointed it to this.

Just to give soma clarity, I'm calling that method with something like this:
```
    public function checkUserRole(User $user, Role $role) {
        return $user->inRole($role);
    }
```

Or maybe I'm not using it correctly?

**Comment by DanVeira** [comment]
This was fixed with commit dc0f3ec.

My package wasn't up to date. Sorry.

**Comment by DanVeira** [comment]
I'm knew to this and it's very confusing for me.

Even when I run` composer update` I still don't get the changes done to that commit, what's going on?

**Comment by brunogaspar** [comment]
Hello @DanVeira 

The reason you're not getting these changes is because they are not in a stable release yet.

To still get these changes you need to either append `@dev` to Sentinel dependency on your `composer.json` file or just change the `minimum-stability` to `dev` on your `composer.json` file.

Hope it helps.

If you still have issues, just let us know.
